### ISSUE TITLE
Auto support ranks

### ISSUE THREAD

**Issue by Tomoli75** [MCDiamondFire/DF-Nicker#1]
No issue template, so here we go.
If enabled in the config, it should make JrHelper, Helper, etc roles, but name them things like Df-Helper and Df-JrHelper. This should be a default setting (enabled hopefully).
It should also automatically demote people with those roles that.. aren't the true role on DF.

:)

**Comment by SiebeDW** [comment]
Im looking in this and I will do a PR for this soon

**Comment by Tomoli75** [comment]
Thanks, make sure it automatically demotes people :)
